//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.18 at 05:25:29 PM EET 
//

package com.eks.WeatherApp.pojo;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}phenomenon"/>
 *         &lt;element ref="{}tempmin"/>
 *         &lt;element ref="{}tempmax"/>
 *         &lt;element ref="{}text"/>
 *         &lt;element ref="{}place" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}wind" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}sea" minOccurs="0"/>
 *         &lt;element ref="{}peipsi" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "phenomenon",
        "tempmin",
        "tempmax",
        "text",
        "place",
        "wind",
        "sea",
        "peipsi"
})
@XmlRootElement(name = "night")
public class Night {

    @XmlElement(required = true)
    protected String phenomenon;
    protected byte tempmin;
    protected byte tempmax;
    @XmlElement(required = true)
    protected String text;
    protected List<Place> place;
    protected List<Wind> wind;
    protected String sea;
    protected String peipsi;

    /**
     * Gets the value of the phenomenon property.
     * 
     * @return
     *         possible object is
     *         {@link String }
     * 
     */
    public String getPhenomenon() {
        return phenomenon;
    }

    /**
     * Sets the value of the phenomenon property.
     * 
     * @param value
     *              allowed object is
     *              {@link String }
     * 
     */
    public void setPhenomenon(String value) {
        this.phenomenon = value;
    }

    /**
     * Gets the value of the tempmin property.
     * 
     */
    public byte getTempmin() {
        return tempmin;
    }

    /**
     * Sets the value of the tempmin property.
     * 
     */
    public void setTempmin(byte value) {
        this.tempmin = value;
    }

    /**
     * Gets the value of the tempmax property.
     * 
     */
    public byte getTempmax() {
        return tempmax;
    }

    /**
     * Sets the value of the tempmax property.
     * 
     */
    public void setTempmax(byte value) {
        this.tempmax = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *         possible object is
     *         {@link String }
     * 
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *              allowed object is
     *              {@link String }
     * 
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the place property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the place property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getPlace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Place }
     * 
     * 
     */
    public List<Place> getPlace() {
        if (place == null) {
            place = new ArrayList<Place>();
        }
        return this.place;
    }

    /**
     * Gets the value of the wind property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wind property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getWind().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Wind }
     * 
     * 
     */
    public List<Wind> getWind() {
        if (wind == null) {
            wind = new ArrayList<Wind>();
        }
        return this.wind;
    }

    /**
     * Gets the value of the sea property.
     * 
     * @return
     *         possible object is
     *         {@link String }
     * 
     */
    public String getSea() {
        return sea;
    }

    /**
     * Sets the value of the sea property.
     * 
     * @param value
     *              allowed object is
     *              {@link String }
     * 
     */
    public void setSea(String value) {
        this.sea = value;
    }

    /**
     * Gets the value of the peipsi property.
     * 
     * @return
     *         possible object is
     *         {@link String }
     * 
     */
    public String getPeipsi() {
        return peipsi;
    }

    /**
     * Sets the value of the peipsi property.
     * 
     * @param value
     *              allowed object is
     *              {@link String }
     * 
     */
    public void setPeipsi(String value) {
        this.peipsi = value;
    }

}
