//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.03.18 at 05:25:29 PM EET 
//


package com.eks.WeatherApp.pojo;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}name"/>
 *         &lt;element ref="{}direction"/>
 *         &lt;element ref="{}speedmin"/>
 *         &lt;element ref="{}speedmax"/>
 *         &lt;element ref="{}gust"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "direction",
    "speedmin",
    "speedmax",
    "gust"
})
@XmlRootElement(name = "wind")
public class Wind {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String direction;
    protected byte speedmin;
    protected byte speedmax;
    protected byte gust;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirection(String value) {
        this.direction = value;
    }

    /**
     * Gets the value of the speedmin property.
     * 
     */
    public byte getSpeedmin() {
        return speedmin;
    }

    /**
     * Sets the value of the speedmin property.
     * 
     */
    public void setSpeedmin(byte value) {
        this.speedmin = value;
    }

    /**
     * Gets the value of the speedmax property.
     * 
     */
    public byte getSpeedmax() {
        return speedmax;
    }

    /**
     * Sets the value of the speedmax property.
     * 
     */
    public void setSpeedmax(byte value) {
        this.speedmax = value;
    }

    /**
     * Gets the value of the gust property.
     * 
     */
    public byte getGust() {
        return gust;
    }

    /**
     * Sets the value of the gust property.
     * 
     */
    public void setGust(byte value) {
        this.gust = value;
    }

}
